### ISSUE TITLE
add NOT Scomber. japonicus to Canto  publication loading

### ISSUE THREAD

**Issue by ValWood** [japonicusdb/japonicus-config#1]
add NOT Scomber. japonicus to Canto  publication loading

**Comment by ValWood** [comment]
Do we want  Canto stuff on the Canto tracker with a japonicus label?

**Comment by ValWood** [comment]
and Stichopus japonicus

**Comment by ValWood** [comment]
Obviously only for future. existing ones can easily be filtered as "wrong organism".

**Comment by ValWood** [comment]
"styrax macrocarpus" which sometimes mentions "Styrax japonicus"

**Comment by ValWood** [comment]
and "Synagrops japonicus"

**Comment by ValWood** [comment]
and "Sicyopterus japonicus"

**Comment by kimrutherford** [comment]
> Do we want Canto stuff on the Canto tracker with a japonicus label?

Let's keep it separate unless there's a Canto bug that need fixing.

**Comment by kimrutherford** [comment]
I did some testing with those filters added.  And I also changed `"Schizosaccharomyces japonicus"` to `("Schizosaccharomyces" AND "japonicus")` which picks up a few extra papers.

How does this look?:
  https://pubmed.ncbi.nlm.nih.gov/?term=(("Schizosaccharomyces"+AND+"japonicus")+OR+"S.+japonicus")+NOT+"Scomber+japonicus"+NOT+"sicyopterus+japonicus"+NOT+"stichopus+japonicus"+NOT+"synagrops+japonicus"+NOT+"styrax+macrocarpus"+NOT+"styrax+japonicus"+NOT+"stichopus+japonicus"+NOT+"sea+cucumber"+NOT+"semanotus+japonicus"

There are still a few false positives.

One of the extra papers is: https://pubmed.ncbi.nlm.nih.gov/26263485/
Which wasn't picked up by our initial query using "Schizosaccharomyces japonicus" because of a typo in the abstract:
```
  Recent work on another member of the same genus, Schisozaccharomyces japonicus, suggests that ...
```
Whoops.

**Comment by ValWood** [comment]
Whoops indeed!

False positive are inevitable, and this isn't a big deal because the number of papers makes triage easy anyway. I get many FP for pombe.

So if Snezka agrees that all the papers are in this list we con continue with this search string.
I can't imagine this string would miss any future papers and if it did they can be added manually.

I am sure we are missing some pombe ones. Sometimes people forget to mention the organism in the title, abstract or keywords (more often than you would imagine!)

**Comment by ValWood** [comment]
I think we can close this?

**Comment by kimrutherford** [comment]
I haven't made a script to do this nightly yet.

**Comment by kimrutherford** [comment]
> I haven't made a script to do this nightly yet.

Done!  It didn't need a script, just a cron entry.
